const MOCK_SUBSCRIPTION_SUCCESS_REDIRECT_URL = 'welcome.html'
const MOCK_SUBSCRIPTION_ERROR_REDIRECT_URL = 'error.html'

process.env.SUBSCRIPTION_SUCCESS_REDIRECT_URL = MOCK_SUBSCRIPTION_SUCCESS_REDIRECT_URL
process.env.SUBSCRIPTION_ERROR_REDIRECT_URL = MOCK_SUBSCRIPTION_ERROR_REDIRECT_URL

module.exports = {
    MOCK_SUBSCRIPTION_ERROR_REDIRECT_URL,
    MOCK_SUBSCRIPTION_SUCCESS_REDIRECT_URL,
}
